name: Auto Merge Dependabot PRs

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
    paths:
      - '.github/workflows/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.2

      - name: Auto-merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
          github-token: ${{ secrets.MY_GITHUB_PAT }}