name: Merge to main

on:
  push:
    branches: [ dev ]

permissions:
  contents: write

jobs:
  merge-to-main:
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Merge dev -> main
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: main
          github_token: ${{ secrets.MY_GITHUB_PAT }}